GOOGLE_CLIENT_ID=448581954011-rg6p1pjrpc890eh7q5lccnrbudsd5fg3.apps.googleusercontent.com
GOOGLE_SECRET_ID=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
STRIPE_SECRET_KEY=sk_test_51Rm6bMHF2oQEzeCPbcNDwzB58bh5X3oCwLyB72zX4YRujFqWrTvCrkWOxMf2i906NQknqWXFjsZdRnWcuNn3KhB200G7GAG1ab

